server:
  port: 8084


spring:
  application:
    name: baidu-zuul

eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka




zuul:
  routes:
    Mr-Li:
      path: /Nice/**
      serviceId: baidu-consumer
